### ISSUE TITLE
tf.contrib.losses.mean_squared_error is deprecated

### ISSUE THREAD

**Issue by njustesen** [Marqt/ViZDoom#130]
Hi.

I just installed tensorflow on Ubuntu with GPU support, and when I run the learning_tensorflow.py example, I get.

File "learning_tensorflow.py", line 107, in __init__
loss = tf.contrib.losses.mean_squared_error(q, target_q_)
AttributeError: 'module' object has no attribute 'mean_squared_error'

It seems it is deprecated. How can it be fixed?

Thanks.

**Comment by ebonyclock** [comment]
What version of tf do you use? I see it is not present in 0.10 and it should work on 0.11 and master. 

Docs to 0.11 say:
"THIS FUNCTION IS DEPRECATED. It will be removed after 2016-10-01. Instructions for updating: Use mean_squared_error."  - sounds like some error in docs.

Since it is still on master branch with doc:
"SOME ARGUMENTS ARE DEPRECATED. They will be removed after 2016-11-25. Instructions for updating: targets is being deprecated, use labels. weight is being deprecated, use weights."
I assume that it replaced some other function and is here to stay.

**Comment by njustesen** [comment]
Thanks. For some reason it was running version 0.9.
