### ISSUE TITLE
Build error on Ubuntu 16.04 LTS amd64

### ISSUE THREAD

**Issue by hholst80** [Marqt/ViZDoom#75]
I'm getting a link error at build on Ubuntu 16.04 LTS. Any ideas?

```
[ 99%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_game.cpp.o
[ 99%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_screen.cpp.o
[ 99%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_shared_memory.cpp.o
[100%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_message_queue.cpp.o
[100%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_main.cpp.o
[100%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/vizdoom_depth.cpp.o
[100%] Linking CXX executable ../../../bin/vizdoom
CMakeFiles/vizdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_stream_decoder@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_end@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_code@XZ_5.0'
collect2: error: ld returned 1 exit status
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8868: recipe for target 'bin/vizdoom' failed
make[2]: *** [bin/vizdoom] Error 1
CMakeFiles/Makefile2:897: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Marqt** [comment]
Looks like liblzma is missing or there is same version mismatch.
What is the output of `dpkg -l | grep lzma`?
Maybe simple `apt-get upgrade liblzma-dev liblzma5 `will solve the problem.

**Comment by hholst80** [comment]
The `apt-get upgrade libzma-dev liblzma5` did not solve the issue. 
```
$ dpkg -l | grep lzma
ii  liblzma-dev:amd64                           5.1.1alpha+20120614-2ubuntu2                        amd64        XZ-format compression library - development files
ii  liblzma5:amd64                              5.1.1alpha+20120614-2ubuntu2                        amd64        XZ-format compression library
ii  lzma-dev                                    9.22-2ubuntu2                                       all          Compression and decompression in the LZMA format - development files
```

**Comment by wjaskowski** [comment]
Does ZDoom alone (http://zdoom.org/wiki/Compile_ZDoom_on_Linux) compile
correctly on your system?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by hholst80** [comment]
Yes it seems to build just fine,

```
$ ./zdoom 
ZDoom 2.9pre-1002-g1703842 - 2016-06-06 10:48:40 +0200 - SDL version
Compiled on Jun  7 2016

M_LoadDefaults: Load system defaults.
Cannot find a game IWAD (doom.wad, doom2.wad, heretic.wad, etc.).
Did you install ZDoom properly? You can do either of the following:

1. Place one or more of these wads in ~/.config/zdoom/.
2. Edit your ~/.config/zdoom/zdoom.ini and add the directories of your
iwads to the list beneath [IWADSearch.Directories]
```

**Comment by wjaskowski** [comment]
So maybe execute  ``ldconfig -p | grep lzma`` and check that the files linked there exist.

**Comment by domluna** [comment]
@wjaskowski I'm having the same issue, on 16.04 as well.

```
ldconfig -p | grep lzma                                     
	liblzma.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/liblzma.so.5
	liblzma.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/liblzma.so
```

**Comment by wjaskowski** [comment]
Do the so files exist?

**Comment by domluna** [comment]
Well from the looks of it liblzma.so.5 does but there's no liblzma.so (with no number postfixes)

```
ls /lib/x86_64-linux-gnu/liblzma.so  
ls: cannot access '/lib/x86_64-linux-gnu/liblzma.so': No such file or directory
```

**Comment by domluna** [comment]
I misread the filepath didn't see the /usr/ prefix for liblzma.so but it's also there.

```
ls /usr/lib/x86_64-linux-gnu/ | grep lzma
liblzma.a
liblzma.so
```

**Comment by wjaskowski** [comment]
But it might be a link pointing at nothing:

```➜  ~ ldconfig -p | grep lzma
liblzma.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/liblzma.so.5
➜  ~ ls -l /lib/x86_64-linux-gnu/liblzma.so.5
➜  ~ ls -l /lib/x86_64-linux-gnu/liblzma.so.5
lrwxrwxrwx 1 root root 16 lis 21  2014 /lib/x86_64-linux-gnu/liblzma.so.5
-> liblzma.so.5.0.0
➜  ~ ls -l /lib/x86_64-linux-gnu/liblzma.so.5.0.0
-rw-r--r-- 1 root root 137400 lut 12  2014
/lib/x86_64-linux-gnu/liblzma.so.5.0.0
```

**Comment by domluna** [comment]
```
ldconfig -p | grep lzma
	liblzma.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/liblzma.so.5
	liblzma.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/liblzma.so

ls  -l /usr/lib/x86_64-linux-gnu/ | grep lzma
-rw-r--r--  1 root root    268574 Feb 12  2014 liblzma.a
lrwxrwxrwx  1 root root        38 Feb 12  2014 liblzma.so -> /lib/x86_64-linux-gnu/liblzma.so.5.0.0

ls  -l /lib/x86_64-linux-gnu/ | grep lzma    
lrwxrwxrwx 1 root root      16 Jan 13 21:13 liblzma.so.5 -> liblzma.so.5.0.0
-rw-r--r-- 1 root root  137400 Feb 12  2014 liblzma.so.5.0.0

 ls -l /lib/x86_64-linux-gnu/liblzma.so.5.0.0 
-rw-r--r-- 1 root root 137400 Feb 12  2014 /lib/x86_64-linux-gnu/liblzma.so.5.0.0

```

Both are symlinked to the same file `liblzma.so.5.0.0`

**Comment by ebonyclock** [comment]
We've installed two separate Ubuntus 16.04 and they didn't suffer from lzma problem. Any ideas/tips how to reproduce it?

**Comment by domluna** [comment]
Hmm, I'm not sure I've been installing it as part of [gym](https://github.com/openai/gym) so I tried just to install VizDoom by itself and the cmake configuration throws some errors.

[Error output](https://gist.github.com/domluna/1d7c3248cb20d64035d62cc2e09789be)

As a side note the readme says gcc 4.6+ required, does this include gcc 5.x? 

gcc (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413 is my default right now. I don't have gcc 4.x installed.

**Comment by ebonyclock** [comment]
Oh, that might be the issue! I remember I once tried it with gcc 5 and something was wrong. However it was long before the release so I even can't remember details. Anyway I'll check this.

**Comment by wjaskowski** [comment]
ViZDoom runs compiled with gcc 5.2.1 without problems on my system.

**Comment by ebonyclock** [comment]
Hmmm same here... I've run it with gym and it works ok.

**Comment by domluna** [comment]
Are you using the default python install? I'm using anaconda but I doubt that would be the issue. I doubt that would be the issue. In any case frustrating on my end :-(

**Comment by ebonyclock** [comment]
I am using the default one but it doesn't sound like python's issue. Run cmake with DBUILD_PYTHON=OFF and we'll know for sure.

**Comment by domluna** [comment]
Ok, I ran it like you said and I get to the original error. 

```
[100%] Linking CXX executable ../../../bin/vizdoom
CMakeFiles/vizdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_stream_decoder@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_end@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_code@XZ_5.0'
collect2: error: ld returned 1 exit status
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8868: recipe for target 'bin/vizdoom' failed
make[2]: *** [bin/vizdoom] Error 1
CMakeFiles/Makefile2:860: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

But earlier in the output I get this

```
Scanning dependencies of target lzma
[ 11%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zArcIn.o
[ 12%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zBuf.o
[ 12%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zCrc.o
[ 12%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zCrcOpt.o
[ 12%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zDec.o
[ 12%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zStream.o
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Bcj2.o
/home/dom/src/ViZDoom/src/vizdoom/lzma/C/Bcj2.c: In function ‘Bcj2Dec_Decode’:
/home/dom/src/ViZDoom/src/vizdoom/lzma/C/Bcj2.c:235:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         SetUi32(p->temp, val);Z
         ^
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Bra.o
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Bra86.o
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/BraIA64.o
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/CpuArch.o
[ 13%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Delta.o
[ 14%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/LzFind.o
[ 14%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Lzma2Dec.o
[ 14%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/LzmaDec.o
[ 14%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/LzmaEnc.o
[ 14%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Ppmd7.o
[ 15%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/Ppmd7Dec.o
[ 15%] Linking C static library liblzma.a
[ 15%] Built target lzma
```

So it links lzma but then I'm guessing calls methods not present in lzma?

**Comment by ebonyclock** [comment]
Somewhat similar problem: https://groups.google.com/forum/#!topic/caffe-users/0PrZlro7QbU maybe it will help.

**Comment by vmonaco** [comment]
I had the same issue and using ld.gold seems to have worked:

Check which linker you're using:
```
ls -l /usr/bin/ld
```

Install gold and set as default:
```
apt-get install binutils-gold
update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 20
update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10
```

Switch between gold and GNU linker:
```
update-alternatives --config ld
```

See also here:
https://github.com/mitchellh/vagrant/issues/5118

**Comment by domluna** [comment]
@vmonaco thanks looks like it works now!

**Comment by wjaskowski** [comment]
@vmonaco thanks for sharing the solution. I wonder now whether this is
problem on the vizdoom or Ubuntu 16.04 side?
